### ISSUE TITLE
Eventviewer errors after redirecting event logs to writecache disk

### ISSUE THREAD

**Issue by thewitscher** [EUCweb/BIS-F#273] opened 2020-08-05 09:42 UTC
massive Eventviewer Errors 23

![grafik](https://user-images.githubusercontent.com/66991062/89397777-8d66e200-d710-11ea-8e68-f6e1bd7a0b84.png)
![grafik](https://user-images.githubusercontent.com/66991062/89397834-a2437580-d710-11ea-8d6f-f1727a5ccb15.png)

**Comment by matthias-schlimm** [comment] 2020-08-05 10:26
Windows 10 1809 and Server 2016 can't reproduce the evventviewer issue

![image](https://user-images.githubusercontent.com/34108484/89402207-cace6e00-d716-11ea-89a4-143b56c0353a.png)

![image](https://user-images.githubusercontent.com/34108484/89402231-d15ce580-d716-11ea-8437-d5bd9cf17e63.png)

**Comment by xenadmin** [comment] 2020-08-05 11:42
I looked at my setup:
- Windows Server 2016
- CVAD 1912.1000
- BIS-F 7.1912.4
- MCSIO activated
- Eventlogs redirected to D:\
- Logs persist betweent reboots
- No errors in eventvwr.msc

**Comment by thewitscher** [comment] 2020-08-06 12:53
I´m facing the event errors 23 even after I restart the Server or Worker. Maybe it is only in my Lab, but I wanted to address it as a precaution.
What about the query errors? 
If you want to switch back the Event Logs to c:\ drive (disabled redirection), I cannot delete the old eventlog folder on the WriteCache disk. I´m getting the following error:
![grafik](https://user-images.githubusercontent.com/66991062/89533885-67b30900-d7f4-11ea-8b56-d6eef9922ae7.png)

**Comment by matthias-schlimm** [comment] 2020-08-24 08:51
@thewitscher any updates on this or can I close this issue ?

**Closed as completed** 2020-11-21 18:50 UTC
Labels: wontfix
