### ISSUE TITLE
No finalize with installed UPL feature in VDA Installation

### ISSUE THREAD

**Issue by thewitscher** [EUCweb/BIS-F#248] opened 2020-06-16 06:57 UTC
With installed UPL feature in the VDA Installation BIS-F finalize isn´t possible. At the end the following error message appears: "Layer finalize is NOT allowed".

**Comment by thewitscher** [comment] 2020-06-16 07:08
[PERS_BISF_WPT_MASTER-W10EX64_20200615-145952.log.log](https://github.com/EUCweb/BIS-F/files/4784947/PERS_BISF_WPT_MASTER-W10EX64_20200615-145952.log.log)
[PREP_BISF_MASTER-W10EX64_20200615-144644.log](https://github.com/EUCweb/BIS-F/files/4784948/PREP_BISF_MASTER-W10EX64_20200615-144644.log)
[PREP_BISF_WPT_MASTER-W10EX64_20200615-144644.log](https://github.com/EUCweb/BIS-F/files/4784949/PREP_BISF_WPT_MASTER-W10EX64_20200615-144644.log)
[PERS_BISF_MASTER-W10EX64_20200615-145952.log](https://github.com/EUCweb/BIS-F/files/4784950/PERS_BISF_MASTER-W10EX64_20200615-145952.log)

**Comment by matthias-schlimm** [comment] 2020-06-16 07:51
please change _BISF.psm1_  - Function _Test-AppLayeringSoftware_

Line 2580-2581:

**old:**
```
Write-BISFLog -Msg "Computer is DomainMember: DomainMember" 
IF (($DomainMember -eq $true ) -and ($CTXAppLayeringRunMode -ne 1)) { $OverrideRunMode = $false } ELSE {$OverrideRunMode = $true } 
```


**new:**
```
Write-BISFLog -Msg "Computer is DomainMember: $DomainMember" 
IF (($UPL -eq $false) -and ($DomainMember -eq $true ) -and ($CTXAppLayeringRunMode -ne 1)) { $OverrideRunMode = $false } ELSE {$OverrideRunMode = $true } 
```

**Comment by matthias-schlimm** [comment] 2020-06-18 04:55
Duplicate of #251

**Closed as completed by matthias-schlimm** 2020-06-18 04:55 UTC
Labels: Type: Bug, Priority: Medium
